### ISSUE TITLE
SongDownloader: Enable download of content in 'Low' and 'Lowest' quality

### ISSUE THREAD

**Issue by Fulch36** [Inrixia/neptune-plugins#30]
Currently, the available quality settings for the SongDownloader plugin, appears to be restricted to a subset of the [AudioQualityEnum](https://github.com/Inrixia/neptune-plugins/blob/master/lib/AudioQuality.ts#L1-L7) values. There is a [comment](https://github.com/Inrixia/neptune-plugins/blob/master/lib/AudioQuality.ts#L30) that appears to explain the lack of MQA format support but both the 'Low' and 'Lowest' formats are also excluded from [validQualitiesSettings](https://github.com/Inrixia/neptune-plugins/blob/master/lib/AudioQuality.ts#L31), seemingly without reason.

Would it be possible to enable the download of content in these lower quality settings?

**Comment by Inrixia** [comment]
Why would you download low if high is available?

**Comment by Inrixia** [comment]
To clarify incase you have misunderstood.

The downloader currently supports downloading low and lower quality files (though tagging/Metadata is not supported atm as the file type is not flac).

But if a file has High quality then the downloader will use that or higher depending on your preference.

I don't really see the use case for having the option to select low explicitly for songs that have High quality.

The main reason the quality selector is there is for analyzing High vs MQA tracks.

**Comment by Inrixia** [comment]
If you can provide a decent reason for explicitly selecting low quality then I'd be happy to either add it or have you add it in a PR.

**Comment by Fulch36** [comment]
Appreciate the speedy response and happy to elaborate on my use case.

I'm in the midst of migrating from Spotify to Tidal and make regular use of the ability to sync playlists offline, to a Wear OS smartwatch for use in the gym. Unfortunately, Tidal do not offer a Wear OS client application of any kind which has led to me seeking out workarounds. In my opinion, this particular listening scenario benefits very little from the increase in quality that FLAC brings over AAC and given the low amount of storage available on current wearables, the lossy format is my preference.

As it stands, I can use the plugin to download content in FLAC but then have to convert it to a lossy format, my aim was to skip this step.

However, I'd completely overlooked the fact that the plugin was having to generate suitable tags for the content. That adds considerably to the work involved here.

**Comment by Inrixia** [comment]
I can work on getting tags supported for the new format. It was something on my todo list, though I do remember running into some problems trying to do so when originally testing low quality support (thus the lack of implementation).

Honestly I'd be curious to see if encoding yourself offers better quality as I feel like it might. But that aside for now re-encoding should work well assuming what you use (ideally ffmpeg) is copying the Metadata it can to the new format.

I'll leave this open as a semi feature request for low quality tagging and the option to explicitly select low as imo it's a worthwhile addition.

**Comment by Inrixia** [comment]
Curiously song encoding and manifest handling has recently been completely changed on Tidal's backend. This I would presume is part of them changing their free streaming tier.

Interestingly all low quality files now seem to be mp3 instead of m4a dash and have been re-encoded (see example below)
![image](https://github.com/Inrixia/neptune-plugins/assets/6373693/0cbfa2d1-bbd2-4d2b-889f-39f8aa112d82)

Considering there is no better source for the above example I guess they just re-encoded at a constant bitrate which seems a bit strange all things considered.

Either way downloading low quality is fixed and using the new manifest types etc, will add a option in settings to explicitly select the desired quality too.

**Comment by Fulch36** [comment]
That was fast! I've not had chance to go through the latest commits to see what was involved but can confirm from a single test case, that the downloading works.

Interestingly, on a single track I've tried, I do still get AAC - whether I go for Low (AAC CBR 320Kb/s) or Lowest (AAC CBR 96Kb/s):
![image](https://github.com/Inrixia/neptune-plugins/assets/9916786/bd49a6dd-d727-43b2-89e3-64e490cc0ff6)

I wasn't aware Tidal had any content in MP3, that's definitely interesting to know. I know they've just announced they're dropping MQA and 360RA but don't think I remember seeing anything about them changing their lower quality encoding. I'd imagine that'll complicate things when it comes to tagging/metadata...

**Comment by Inrixia** [comment]
Due to the mess that is trying to deal with metadata for non flac files I'm not going to add metadata embedding for low etc files.

The ability to select Low/Lower in download settings has been added in https://github.com/Inrixia/neptune-plugins/commit/64bfbf1e8cb069fc7478686d6e00fed656c4378c so I will close this for now.

Do feel free to reply or continue the discission if anything else comes up :)

**Comment by Inrixia** [comment]
> I wasn't aware Tidal had any content in MP3...

Yes! Its weird, it seems to be a strange outlier atm that I only happened upon as my **Low** test file happened to use it, maybe they are migrating away from dash?

You can see the test file here: https://tidal.com/browse/track/10575447

Weirdly the **Low** quality is mp3 while **Lower** is still m4a. Very strange...

**Comment by Inrixia** [comment]
There isnt really a nice library for tagging m4a content so for now I have held off implementing it due to the very small number of tidal tracks that are actually only **Low** quality.

There is a mp3 one which I tested that works, but since so far its only one file I haven't bothered fully implementing it yet.
